### ISSUE TITLE
azure/login@v1 and azure/CLI@v1 should be consistent

### ISSUE THREAD

**Issue by jludvice** [Azure/login#104]
Please align `azure/login@v1` and `azure/CLI@v1`. It's really strange and not user friendly.

Given workflow where I first use `azure/CLI@v1` to show current az version and then use `azure/login@v1` it behaves quite weird.

`az version` actually shows latest version because this action actually pulls and runs microsoft docker image with azure cli,
but then the `azure/login@v1` action fails because this one relies on `az` command being installed on self-hosted github runner.

```
    - name: show az version
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az version

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.SECRET }}
```

In my case the  ` azure/login@v1` will fail on `az` command not being available because my runners are quite clean and `az` is not installed.

What is the reason to forcing users to both manage `az` on the hosts and also require having docker installed and pull docker images for actually performing any az actions?

I believe `azure/login` and `azure/cli` should use consistent approach in this case.

**Comment by jludvice** [comment]
```
Run azure/login@v1
  with:
    creds: ***
    enable-AzPSSession: false
    environment: azurecloud
    allow-no-subscriptions: false
  env:
    NOT_RELEVANT: "..."

Error: Az CLI Login failed. Please check the credentials. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows
Error: Error: Unable to locate executable file: az. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

**Comment by AlexDHoffer** [comment]
This is happening to me as well on my self-hosted runner. It is bizarrely challenging to use these simple features.

**Comment by orenzi-tr** [comment]
> This is happening to me as well on my self-hosted runner.

I also had this issue running on a windows Github self-hosted runner. 
I managed to get it to work by changing the Github-runner server "Log On" as setting to run under a local user account instead of running as Local System.

This isn't an ideal solution on my part, so I guess its something with windows PATH issue if it can't find the executable.

**Comment by khalidiml** [comment]
I am also facing this problem. I have checked the credentials. The creds are valid.
```
- uses: azure/login@v1
  with:
      creds: ${{ env.AZURE_CREDENTIALS }}

Error: Az CLI Login failed. Please check the credentials. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows
Error: Unable to locate executable file: az. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

**Comment by davetapley** [comment]
I just lost an hour because of the `Please check the credentials.` message,
when in reality it was just that the [`act`](https://github.com/nektos/act) runner I was using didn't have `az` installed 😞 

Even if we can't get self installing, can we at least check for `az` and abort with a clearer error message?
I think it's as simple as checking catching here:
https://github.com/Azure/login/blob/db989b30605ff229e9f1de292a8f0aa043ee48b1/src/main.ts#L44

Because [`which`](https://github.com/actions/toolkit/blob/main/packages/io/src/io.ts#L186-L187) says:
> If you check and the tool does not exist, it will throw.

**Comment by BALAGA-GAYATRI** [comment]
`Azure/login` action is only responsible for logging into azure. `Azure/cli` has a different approach of pulling the latest docker image and executing cli commands. While the design of both the actions is different currently `az` needs to be present on the runner to leverage login action. Inorder to help the users to figure out the reason for failure, we have added this statement in the error response and released a new version[ v1.4.3](https://github.com/Azure/login/releases/tag/v1.4.3) and updated v1 version also with the same.

**Comment by apgapg** [comment]
But how do we install az on self hoster runner?
I cant find much straight forward docs

**Comment by Udhayarajan** [comment]
```yml
#      need CLI as Azure Login requires it in self-hosted runners
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
```

**Comment by Udhayarajan** [comment]
> But how do we install az on self hoster runner? I cant find much straight forward docs


```yml
       # need CLI as Azure Login requires it,  in self-hosted runners
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
```
