### ISSUE TITLE
Az CLI Login failed

### ISSUE THREAD

**Issue by swethmandava** [Azure/login#107]
```
Run azure/login@v1
  with:
    creds: ***
    allow-no-subscriptions: true
    enable-AzPSSession: false
    environment: azurecloud
/usr/bin/az cloud set -n azurecloud
Done setting cloud: "azurecloud"
Error: Az CLI Login failed. Please check the credentials. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows
Error: Error: Error: The process '/usr/bin/az' failed with exit code 1
```

My github action fails with the above error! what am i missing ?

```
name: Benchmarking
on:
  push:
    branches:
      - dev
      - main
      - swetha/latency_setup
  pull_request:
    branches:
      - dev
      - main
jobs:
  benchmark:
    name: Run pytest-benchmark benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: "KEYVAULT" # name of key vault in Azure portal
          secrets: 'Username, Password'   # comma separated list of secret keys to fetch from key vault
        id: AzureSecrets
```
