### ISSUE TITLE
Azure login takes ~ 3.50 minutes which is too long for simple login..

### ISSUE THREAD

**Issue by deepend-dev** [Azure/login#119]
Below snippets hold the session for almost 4 minutes - 

```powershell
Run azure/login@v1
/usr/bin/az cloud set -n azurecloud
Done setting cloud: "azurecloud"
Running Azure PS Login
/usr/bin/pwsh -Command try ***
            $ErrorActionPreference = "Stop"
            $WarningPreference = "SilentlyContinue"
            $output = @***
            $data = Get-Module -Name Az.Accounts -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1
            $output['AzVersion'] = $data.Version.ToString()
            $output['Success'] = "true"
        ***
        catch ***
            $output['Error'] = $_.exception.Message
        ***
        return ConvertTo-Json $output
***
  "Success": "true",
  "AzVersion": "2.3.0"
***
```

It has probably happening because of  ` $data = Get-Module -Name Az.Accounts -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1 ` .

May be we can use a container which already has Az module installed so it doesnt take that long to download Az.Account module?

**Comment by dkirrane** [comment]
I have same issue. In my case it's consistently > 1min to login
```
      - name: Azure Login
        uses: Azure/login@v1.3.0
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
          enable-AzPSSession: true
```
