### ISSUE TITLE
Doesn't work with SP's generated from Azure CLI v2.29.1?

### ISSUE THREAD

**Issue by JasonFreeberg** [Azure/login#161]
I updated my Azure CLI to v2.29.1 yesterday. I'm setting up a demo to deploy to Azure, but the login action keeps failing. I've done this many times before, so I'm not sure why it's not working. Possibly related to this change: https://github.com/Azure/azure-cli/issues/19892? Looks like there's a recent breaking change in AAD.

1. I generated a service principal using the following command:
    
    ```bash
    az ad sp create-for-rbac \
        --name "{sp-name}" \
        --sdk-auth \
        --role contributor \
        --scopes /subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP
    ```
    
    Which gave me a JSON with this shape:
    
    ```json
    {
      "clientId": "",
      "clientSecret": "",
      "subscriptionId": "",
      "tenantId": "",
      "activeDirectoryEndpointUrl": "",
      "resourceManagerEndpointUrl": "",
      "activeDirectoryGraphResourceId": "",
      "sqlManagementEndpointUrl": "",
      "galleryEndpointUrl": "",
      "managementEndpointUrl": ""
    }
    ```

2. I set it as a secret named `AZURE_CREDENTIALS`
3. I set up the login action:

    ```yaml
      publish:
        runs-on: ubuntu-latest
        needs: build
        
        steps:
          - name: Azure Login
            uses: azure/login@v1
            with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}
    ```

4. And it fails with this error: 
    
    ```text
    /usr/bin/az cloud set -n azurecloud
    Done setting cloud: "azurecloud"
    Error: Az CLI Login failed. Please check the credentials. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows
    Error: Error: Error: The process '/usr/bin/az' failed with exit code 1
    ```

CLI info:

```text
azure-cli                         2.29.1

core                              2.29.1
telemetry                          1.0.6

Extensions:
webapp                             0.4.0

Python location '/opt/az/bin/python3'
Extensions directory '/home/jasonfreeberg/.azure/cliextensions'

Python (Linux) 3.6.10 (default, Oct 21 2021, 06:49:22)
[GCC 7.5.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

Live repro: https://github.com/JasonFreeberg/workshop-migrate-jboss-on-app-service/runs/4028177462?check_suite_focus=true
