### ISSUE TITLE
Could not retrieve credential from local cache for service principal

### ISSUE THREAD

**Issue by JontyMC** [Azure/login#162]
Our github actions stopped working today with the error:

> ERROR: Could not retrieve credential from local cache for service principal **********. Run `az login` for this service principal.

I've tried recreating the service principal, with no luck.

**Comment by edwardgronroos** [comment]
We're experienceing the same problem, something broke with the new Azure Cli version released today?

**Comment by JontyMC** [comment]
> We're experienceing the same problem, something broke with the new Azure Cli version released today?

Looks this way, pinning the CLI action to last version works:

```
- name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.29.2
          inlineScript: ...
```
