### ISSUE TITLE
Subscription id for azure login action using OIDC

### ISSUE THREAD

**Issue by aramase** [Azure/login#163]
Could you help clarify why the azure subscription id is required in the workflow in addition to the tenant id and client? Ideally, I should be able to deploy beyond subscription boundaries? 

Ref: https://github.com/marketplace/actions/azure-login#sample-workflow-that-uses-azure-login-action-using-oidc-to-run-az-cli-linux

```yaml
      - name: 'Az CLI login'
        uses: azure/login@v1.4.0
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}
```
