### ISSUE TITLE
Az CLI Error when using OIDC

### ISSUE THREAD

**Issue by thepaulmacca** [Azure/login#184]
Hi, I've hit a bit of a weird issue. I'm deploying bicep files using some reusable workflows https://github.com/ops-to-dev/actions-reusable-workflows/blob/main/.github/workflows/bicep-deploy.yml and the `validate` job logs in fine, but the `deploy` job fails with the below error:

![image](https://user-images.githubusercontent.com/41340540/144399555-a1bc180e-3018-45a0-afa9-c08e736493c4.png)

I'm not sure why it works for one job but not the other. I've been using the script that was created here https://github.com/jongio/github-azure-oidc

This is the workflow that i'm using to call the above workflow:

```yaml
name: deploy-aks-baseline-cluster

on: 
  push:
    branches: 
    - main
    paths:
    - 'deploy/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  # Lint the Bicep file
  lint: 
    uses: ops-to-dev/actions-reusable-workflows/.github/workflows/bicep-lint.yml@main

  # Deploy to the Dev environment
  deploy-dev:
    uses: ops-to-dev/actions-reusable-workflows/.github/workflows/bicep-deploy.yml@main
    needs: lint
    with:
      environmentName: dev
      environmentType: nonprod
      resourceGroupName: rg-aks-tpm-dev-uks
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
```
Do you have any ideas on what the issue could be?

Thanks

**Comment by BALAGA-GAYATRI** [comment]
Hey @thepaulmacca , the issue here is `validate` job is directly running on main for which you have setup federated credentials, but for the `deploy` job you are using environment -
```yaml
deploy:
    needs: validate
    environment: ${{ inputs.environmentName }}
    runs-on: ubuntu-latest
```
which would require another federated credential setup in azure. I could see in [your script](https://github.com/jongio/github-azure-oidc/blob/main/oidc.sh#L88-L90) FIC(federated identity credentials) were set for only`pull_request` and `refs/heads/main` in subject claims. Now when you use environments you need one more with the `"subject":"repo:<org>/<repo-name>:environment:Production"`. 

Please refer- https://github.com/Azure/login#microsoft-graph for more details.
