### ISSUE TITLE
Allow exporting of OIDC service principal credentials for non-azure-cli applications

### ISSUE THREAD

**Issue by troyready** [Azure/login#188]
It would be nice if the `addSpnToEnvironment` option from the [Azure Devops Login Task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops) (or something like it) was supported so that non-azure-cli apps could use the generated credentials.

For context, in case it's helpful, I'm trying to replicate the [workaround detailed here](https://stackoverflow.com/a/61337144) that puts the credentials in a format that Terraform can use.

**Comment by mikeviviani** [comment]
I'm also interested into this topic. 
My use case is able to pass credential to a reusable workflow. The caller will authenticate using OIDC federated credential and than call a reusable workflow to create pre-defined pieces in Azure like VM, Storage Account or AKS cluster.
So that an application team who wants a VM in Azure needs call a reusable pre-existing workflow created by Azure Platform Owners, just passing few parameters and app credentials

**Comment by BALAGA-GAYATRI** [comment]
You can use the environment variables in your workflow and initialize them with your SPN details. This adds them to the workflow environment. @mikeviviani This helps you with reusable workflows case as well. Refer [environment variables](https://docs.github.com/en/actions/learn-github-actions/environment-variables#about-environment-variables) for more details. You may also refer to this [example](https://github.com/Azure/ResourceModules/blob/c5e6065a96035c56df59482392c52fe91140f715/.github/workflows/ms.web.sites.yml#L27-L34) for better understanding.
Hope this helps with the concern. Closing the issue.

**Comment by Adam-D-Lewis** [comment]
In case this helps others, I was able to use OIDC service principal credentials for a non-azure-cli applications by setting ARM_USE_OIDC: "true" on the step that I wanted to use OIDC credentials for.

```
    	# my github action workflow
    	...

      - name: 'Azure login'
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Integration Tests
        run: |
          terraform deploy 
        env:
          NEBARI_SECRET__default_images__jupyterhub: "quay.io/nebari/nebari-jupyterhub:${{ env.NEBARI_IMAGE_TAG }}"
          NEBARI_SECRET__default_images__jupyterlab: "quay.io/nebari/nebari-jupyterlab:${{ env.NEBARI_IMAGE_TAG }}"
          NEBARI_SECRET__default_images__dask_worker: "quay.io/nebari/nebari-dask-worker:${{ env.NEBARI_IMAGE_TAG }}"
          ARM_CLIENT_ID: ${{ env.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: "true"
          CLOUDFLARE_TOKEN: ${{ env.CLOUDFLARE_TOKEN }}
```
