### ISSUE TITLE
Login using OpenID Connect (OIDC) based Federated Identity Credentials not working (Login using Azure Service Principal with a secret works)

### ISSUE THREAD

**Issue by spacecat** [Azure/login#213]
I'm trying to run this example workflow from https://github.com/marketplace/actions/azure-login:

Note that I'm using `workflow_dispatch` instead of `push` but that should not matter.

```
# File: .github/workflows/OIDC_workflow.yml

name: Run Azure Login with OIDC
on:
     workflow_dispatch:

permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd 
```

I've registered my app according to:

https://github.com/marketplace/actions/azure-login#configure-a-service-principal-with-a-federated-credential-to-use-oidc-based-authentication

and

https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app

but I keep getting the following error:

`Error: : No subscriptions found for ***.`

`Error: Az CLI Login failed. Please check the credentials and make sure az is installed on the runner. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows`

I also tried creating the credentials using the Microsoft Graph method:

https://github.com/marketplace/actions/azure-login#microsoft-graph

This didn't work either.

I've no idea what I'm doing wrong. I read the article at least 10 times and created/registered an app in Azure portal/using the Azure CLI a dozen times but I'm stuck at that error I pasted above.

Any ideas why it's failing?

Azure Login does work with https://github.com/marketplace/actions/azure-login#configure-a-service-principal-with-a-secret however.

It would be nice if it could work with OIDC as well since that's the recommended method going forward.

Please let me know if you need help troubleshooting this.
