### ISSUE TITLE
Feature request: Add parameter for `client-secret`

### ISSUE THREAD

**Issue by MariusStorhaug** [Azure/login#227]
Please add a parameter/input for `client-secret` removing the need for `creds` which is suggestion use of json data structure, which is not recommended by the GitHub team.

**Comment by klyse** [comment]
Struggling exactly there. I'd like to configure ClientID and Secret instead of storing a json block in the Action Secrets. Any workarounds available?

This is not really working but I am unable to get detailed logs to why.
```yml
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        creds: >
          {
            "tenantId": "${{ secrets.azure_tenant_id }}",
            "clientSecret": "${{ secrets.azure_client_secret }}",
            "clientId": "${{ secrets.azure_client_id }}",
            "subscriptionId": "${{ secrets.azure_subscription_id }}"
            "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
            "resourceManagerEndpointUrl": "https://management.azure.com/",
            "activeDirectoryGraphResourceId": "https://graph.windows.net/",
            "sqlManagementEndpointUrl": "https://management.core.windows.net:8443/",
            "galleryEndpointUrl": "https://gallery.azure.com/",
            "managementEndpointUrl": "https://management.core.windows.net/"
          }
```
