### ISSUE TITLE
The key 'id-token' is not allowed

### ISSUE THREAD

**Issue by januszj** [Azure/login#228]
In GitHub Enterprise Server 3.4.3 using self hosted runners, when I try to use login action:

```yaml
buildImage:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Azure login
              uses: azure/login@v1.4.3
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            - name: Build and push image to ACR
              run: |
                az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }} .
```

I'm getting error message:
The workflow is not valid. .github/workflows/azure-kubernetes-service-helm.yml (Line: 24, Col: 13): The key 'id-token' is not allowed .github/workflows/azure-kubernetes-service-helm.yml (Line: 40, Col: 13): The key 'id-token' is not allowed

![image](https://user-images.githubusercontent.com/1262428/171606028-da0326df-773d-44b0-a4bd-ff9911753d9e.png)

Is there a workaround for this  ?
