### ISSUE TITLE
Does not add Az module path if GitHub OIDC login is used.

### ISSUE THREAD

**Issue by JustinGrote** [Azure/login#231]
```yaml
name: ▶️Deploy
on:
  push:
    branches:
      - main
      - ci

#Required for OIDC operations
permissions:
      id-token: write
      contents: read

jobs:
  deploy:
    name:  👷‍♂️Deploy to Azure
    environment: development
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: 💻Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: Az Test
        run: |
          $env:PSModulePath
          Get-Command Get-AzResourceGroup
```

## Workaround

```yaml
      - name: ➕Add Az Module to Path
        run: |
          #PowerShell Script (Workaround for: https://github.com/Azure/login/issues/231)
          function Set-GhEnvVar($Name, $Value) {"$Name=$Value" >> $env:GITHUB_ENV}

          if ($isMacOS) {throw "Not supported on MacOS"}
          $azBasePath = $isLinux ? "/usr/share" : "C:\Modules"
          $azModule = Get-ChildItem -Directory "$azBasePath/az*" -ErrorAction Stop | Select-Object -Last 1
          $newPSModulePath = $azModule.FullName,$env:PSModulePath -join [io.path]::PathSeparator
          Set-GhEnvVar 'PSModulePath' $newPSModulePath
```
![image](https://user-images.githubusercontent.com/15258962/172265270-d49690b0-2bd1-4c14-b5b5-ade39d0e2d1d.png)
