### ISSUE TITLE
Recieving error when loging in to Azure

### ISSUE THREAD

**Issue by Avrohom613** [Azure/login#256]
Hi
I'm testing a very simple yaml workflow using `nektos/act` trying to login to Azure and I'm receiving an error on the login step
`Error: The runs.using key in action.yml must be one of: [composite docker node12], got node16`

Here is the yaml:
```
name: Test-Build
on:
  push:
    branches:
      - master

jobs:
  test-api:
    runs-on: ubuntu-latest
    strategy:
    matrix:
      node-version: [16.x]

    steps:
    - name: Install tools for nektos act local testing run
      if: env.ACT
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
```

I have my secrets file set up, I tried running it on ubuntu using node 16..
This has worked in the past. Am I doing something wrong, or is this an actual issue?
