### ISSUE TITLE
Unable to login to Azure with federated credentials

### ISSUE THREAD

**Issue by georgekosmidis** [Azure/login#280]
As of this morning (sometime after 10:30 CET), all pipelines that use the `Azure/login@v1.4.5` action, fail to login with federated credentials:

```
    - name: azure-login
      uses: Azure/login@v1.4.6
      with:
        client-id: ${{ secrets.azureGithubClientId }}
        tenant-id: ${{ secrets.azureTenantId }}
        subscription-id: ${{ secrets.azureSubscriptionId }}
        enable-AzPSSession: true
```

results in
```
Run Azure/login@v1.4.5
  with:
    client-id: ***
    tenant-id: ***
    subscription-id: ***
    enable-AzPSSession: true
    environment: azurecloud
    allow-no-subscriptions: false
    audience: api://AzureADTokenExchange
Using OIDC authentication...
Federated token details: 
 issuer - https://token.actions.githubusercontent.com 
 subject claim - repo:***/***:environment:Dev
/usr/bin/az cloud set -n azurecloud
Done setting cloud: "azurecloud"
Running Azure PS Login
/usr/bin/pwsh -Command try {
            $ErrorActionPreference = "Stop"
            $WarningPreference = "SilentlyContinue"
            $output = @{}
            $data = Get-Module -Name Az.Accounts -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1
            $output['AzVersion'] = $data.Version.ToString()
            $output['Success'] = "true"
        }
        catch {
            $output['Error'] = $_.exception.Message
        }
        return ConvertTo-Json $output
{
  "AzVersion": "2.10.3",
  "Success": "true"
}
Error: Azure PowerShell Login failed. Please check the credentials and make sure az is installed on the runner. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows"
```
