### ISSUE TITLE
GitHub Enterprise Server External OIDC endpoint failed

### ISSUE THREAD

**Issue by Ravio1i** [Azure/login#283]
So I've st up oidc following the documentation https://docs.github.com/en/enterprise-server@3.7/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure

## Error

However when using it i run into the following error:
```bash
Using OIDC authentication...
Federated token details: 
 issuer - https://<GITHUB_ENTEPRRISE_URL>/_services/token 
 subject claim - repo:<MY_ORG>/<MY_REPO>:environment:azure
/usr/bin/az cloud set -n azurecloud
Done setting cloud: "azurecloud"
Error: : AADSTS501661: Request to External OIDC endpoint failed.
```

## Usage:

```yaml
on:
  workflow_dispatch:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: linux
    environment: azure
    steps:
      - run: az version  
      - name: 'Az CLI login'
        uses: actions/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get az vmss list
        run: az vmss list
```

Azure configuration of federated credential
![Screenshot from 2022-12-16 17-33-19](https://user-images.githubusercontent.com/45916614/208145971-f0f5456d-6546-4b5d-8db0-581f5975c54d.png)

When changing the Issuer to `https://<GITHUB_ENTEPRRISE_URL>/_services/token/` with an appended `/` the error messages changes to 

```bash
AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: 'https://<GITHUB_ENTEPRRISE_URL>/_services/token'. Assertion Subject: 'repo:<MY_ORG>/<MY_REPO>:environment:azure'. Assertion Audience: 'api://AzureADTokenExchange'. https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation
```

Where the values of subject and audience are completely the same as configured in azure federeated
