### ISSUE TITLE
Different authorization to Graph API with OIDC authentication compared to `az login` with secret

### ISSUE THREAD

**Issue by v3gard** [Azure/login#288]
_Disclaimer: This is likely not a bug, but resolving this issue would likely result in better documentation for the project._

I'm trying to figure out why my client has different authorization levels depending on which authentication mechanism I'm using to get an access token. I haven't been able to find documentation supporting that these two authentication mechanisms would result in different authorization levels. 

In both cases I'm using a service principal and not a managed identity. My goal is to access the Graph API and read secret expiration dates from Github. This works as expected from the Azure CLI (on my local computer with a service principal login), but not using azure/login.

The two methods I'm using for authentication are:
1. OIDC authentication via Github and azure/login action, which returns a forbidden message when I try to access the Graph API
2. AZ CLI login using app secret, which works as expected

## Access token claims

After I've received an access token in these two systems, the claims typically look like this. I've scrambled identifying information, but if this is relevant it can likely be disclosed:

|Azure CLI with secret|azure/login action with OIDC|
|-|-|
|![image](https://user-images.githubusercontent.com/343078/211749106-8bf6e731-ea56-44bb-8750-f3da89e66d44.png)|![image](https://user-images.githubusercontent.com/343078/211749146-ca4020da-1713-4a80-8422-20cbf039a538.png)|

Note that I'm using the same version of the Azure CLI with both methods.

# azure/login configuration

```yaml
   steps:
      - name: Debug AZ CLI Login
        run: |
          echo "Using AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}" | sed -r 's/(.{0})(.{30})$/\1***/'
          echo "Using AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}" | sed -r 's/(.{0})(.{30})$/\1***/'
          echo "Using AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}" | sed -r 's/(.{0})(.{30})$/\1***/'
      - name: AZ CLI Login
        uses: azure/login@v1
        with: 
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Check out main branch
        uses: actions/checkout@v3
        with:
          ref: chore/access-app-registrations-from-github
      - name: Create Pull Request
        shell: bash
        env:
            GITHUB_TOKEN: ${{ github.token }}
        run: |
            az version
            az account get-access-token | jq -R 'split(".") | .[1] | @base64d | fromjson' 2>/dev/null || true
            az rest --method get --url https://graph.microsoft.com/v1.0/applications/${{ secrets.AZURE_CLIENT_ID }} | jq -r .passwordCredentials[].endDate
```

# Forbidden

Using both methods, I'm trying to run this command.

```bash
az rest --method get --url https://graph.microsoft.com/v1.0/applications/{AZURE_CLIENT_ID}
```

The `AZURE_CLIENT_ID` I pass to the API is the same client id I'm using to authenticate.

This works fine from the Azure CLI when I log in using a secret, as shown below, but not when I'm using an access token from a OIDC (as shown above). In the latter case, I get this error:

`ERROR: Forbidden({"error":{"code":"Authorization_RequestDenied","message":"Insufficient privileges to complete the operation.","innerError":{"date":"2023-01-10T14:38:23","request-id":"***","client-request-id":"***"}}})`

![image](https://user-images.githubusercontent.com/343078/211752133-1fe286e2-547f-47c2-8193-0d6334a0b4d2.png)

# Summary

Why am I not authorized to access the Graph API when I use an OIDC access token from Github, when it works fine with an access token from the Azure CLI (where I authenticated using a secret)?
