### ISSUE TITLE
ERROR: The cloud 'azurechinacloud' is not registered In Github Action runs-on: self-hosted 

### ISSUE THREAD

**Issue by LuBu0505** [Azure/login#291]
When use the "Azure Login" action in Github Action and set the environment to AzureChinaCloud. This action host by self VM which deploy in China Azure VM.

the host linux version is :  centos7.8

The error message as below
```
Run azure/login@v1
  with:
    creds: ***
    environment: AzureChinaCloud
    enable-AzPSSession: false
    allow-no-subscriptions: false
    audience: api://AzureADTokenExchange
  env:
    SUBMODULE_NAME: admin-api
    IMAGE_NAME: adminapi-serving
    JAVA_VERSION: 11.0.14
    CLOUD_ENV: AzureChinaCloud
    ACR_NAME: ce2cndatacrnpodp01.azurecr.cn
    AKS_NAME: CE2-CNFSC-AKS-DV-ESIGN
    AKS_RESOURCE_GROUP: CE2-CNFSC-RG-DV-ESIGN
    DEPLOYMENT_NAME: test-aks
    DEPLOYMENT_YML: taks.yml

/usr/bin/az cloud set -n azurechinacloud
ERROR: The cloud 'azurechinacloud' is not registered.
Error: Az CLI Login failed. Please check the credentials and make sure az is installed on the runner. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows
```

We use the below .yaml file

```
#modify the file to run again 1
on: [push]

name: AzureCLISample

jobs:

  build-and-deploy:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    
    steps:
    
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        environment: AzureChinaCloud
    
```

**Ask**
If separate run the "az cloud set -n azurechinacloud" in the self linux vm. no this error " The cloud 'azurechinacloud' is not registered."

Why is it appear Github Action? How to resolve it?

Thanks,
