### ISSUE TITLE
Azure Login Action Fails if Azure CLI Action is Called First

### ISSUE THREAD

**Issue by parallo-mattallford** [Azure/login#306]
Hi team,

We recently came across an issue for a customer where the `azure/login@v1` was failing to log in, and would result in the following error message:

```
Error: Az CLI Login failed. Please check the credentials and make sure az is installed on the runner. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows
```

We performed quite a bit of troubleshooting, and then noticed in their workflow, prior to the `azure/login@v1` action, they were running an Azure CLI action to check the version of the Azure CLI. A sample of this workflow is shown below:

```
name: Failing Azure Login Action

on:
  workflow_dispatch:

jobs:
  build:
    name: Testing Azure Login Action
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: az version
        uses: azure/cli@1.0.4
        with:
          azcliversion: latest
          inlineScript: |
            echo $(az --version)

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
```

While troubleshooting, we noticed if we removed the `azure/cli` action, that the `azure/login` action now worked as expected, and logged in to Azure.

I've created a repo [here](https://github.com/parallo-mattallford/azure-login-test/tree/main/.github/workflows) with two workflow files, one that has the `azure/cli` action, and one that doesn't. In the [actions tab](https://github.com/parallo-mattallford/azure-login-test/actions) on this repo, you can see that one of the workflows runs OK, while the other one doesn't.

We noticed this was the same no matter if we tried OIDC login or alternate methods for passing the credential values for the `azure/login` command.

Is there a reason why this is occurring? I was hoping to see a more verbose error message as to why the `azure/login` action is failing, but even with debug logging enabled in GitHub Actions, it doesn't provide us with much information. My only _guess_ at this point is that maybe the container being used for the `azure/cli` action isn't being cleaned up properly, or is causing some sort of conflict with the `azure/login` action? I know this is a bit of a corner case, as it wouldn't be a standard operation to run any Azure CLI commands prior to performing the login action, but I thought it was worth raising as an issue regardless.

Please let me know if any further information is required which could assist with troubleshooting.
