### ISSUE TITLE
How to generate AZURE_CREDENTIALS for updating app registration?

### ISSUE THREAD

**Issue by VitaliyPotapov** [Azure/login#308]
According to readme I can generate credentials for accessing resource group:
```
   az ad sp create-for-rbac --name "myApp" --role contributor \
                            --scopes /subscriptions/{subscription-id}/resourceGroups/{resource-group} \
                            --sdk-auth
```
But I need credentials for updating app registration (per [this instruction](https://learn.microsoft.com/en-us/answers/questions/476151/is-it-possible-to-create-a-redirect-uri-via-an-api)). I can't find in Azure portal the scope for app registration I need to update.

Could you help how to setup azure/login to update app registration?

Thanks in advance!

**Comment by MoChilia** [comment]
Hi @VitaliyPotapov! Let me first figure out what your question is.

If you want to **update the Redirect URI** for app registrations in Azure portal, you can go to the "Authentication" section on the left-hand menu, click the "Add a platform" button and enter the Redirect URI of the application. 

If you want to **check the credential** like client secret of your service principal, I am afraid you can't do so. Client secrets **cannot be viewed, except for immediately after creation.** If you forgot the secret, you can reset a new secret by going to the "Certificates & secrets" section on the left-hand menu, clicking on the "Client secrets" tab and selecting "New client secret". Be sure to save the secret when created before leaving the page this time.

For "**how to setup azure/login to update app registration?**", I think the Azure/login action is not a great choice for you to update app registration. If you want to achieve this in a workflow, you can use [Azure/cli](https://github.com/Azure/cli) by running the az cli command [`az ad sp update`](https://learn.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az-ad-sp-update).

**Comment by VitaliyPotapov** [comment]
> For "how to setup azure/login to update app registration?", I think the Azure/login action is not a great choice for you to update app registration. If you want to achieve this in a workflow, you can use [Azure/cli](https://github.com/Azure/cli) by running the az cli command [az ad sp update](https://learn.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az-ad-sp-update).

My question is this one. I need to run command like the following:
```
az rest --method PATCH --uri 'https://graph.microsoft.com/v1.0/applications/<APP REG OBJECT GUID (object ID not the App ID)>' --headers 'Content-Type=application/json' --body '{"spa":{"redirectUris":["https:<APP DOMAIN (and port if needed)>"]}}'
```
How can I get AZURE_CREDENTIALS to run that command in github action?

**Comment by MoChilia** [comment]
Are you looking for a command to **get** AZURE_CREDENTIALS of the application you updated by running the command above in a workflow?
If so, I am afraid you can't get AZURE_CREDENTIALS again except for immediately after creation. And I don't think there is any change on the AZURE_CREDENTIALS of the application you updated.

Or are you trying to **pass** the AZURE_CREDENTIALS to the command to add redirect URLs? If you have signed in the correct Azure account, there is no need to pass the AZURE_CREDENTIALS again when you update an application.  You can refer to the steps in [Register a client application using CLI and REST API](https://learn.microsoft.com/en-us/azure/healthcare-apis/register-application-cli-rest) and run these scripts by using [Azure/cli](https://github.com/Azure/cli).

**Comment by VitaliyPotapov** [comment]
I just need to get `azure/login` github action working for updating redirect urls. 
Per documentation I need to setup `AZURE_CREDENTIALS` in github secrets and pass it to `azure/login`.

Imagine I have existing app registration with `ObjectId = 12345`.
I want to get the following github action working:

```yaml
# File: .github/workflows/workflow.yml

on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az rest --method PATCH --uri 'https://graph.microsoft.com/v1.0/applications/12345' --headers 'Content-Type=application/json' --body '{"spa":{"redirectUris":["https://mydomain.com"]}}'
```

What command should I use to get `AZURE_CREDENTIALS`?
