### ISSUE TITLE
Cannot find valid federated identity 

### ISSUE THREAD

**Issue by riskpoint-per** [Azure/login#360]
I am using a federated identity which I successfully use for other azure deployments.

In this very case I keep getting the following error:
### Error
```sh
Using OIDC authentication...
Federated token details: 
 issuer - https://token.actions.githubusercontent.com/ 
 subject claim - ****
/usr/bin/az cloud set -n azurecloud
Done setting cloud: "azurecloud"
Error: : AADSTS700[21](https://github.com/******)1: No matching federated identity record found for presented assertion issuer 'https://token.actions.githubusercontent.com/'. Please check your federated identity credential Subject, Audience and Issuer against the presented assertion. https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation
```

### Usage

```yaml
on:
  push:
    branches:
    - dev

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: az version  
      - name: 'Az CLI login'
        uses: actions/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
```

These are credentials I have been using for a while, and certain they are a correct as they are been used for several azure deployments, I am just not sure what the issue is here.
