### ISSUE TITLE
OIDC Login Logs: Error: undefined. Please make sure to give write permissions to id-token in the workflow. When run on Dedicated Runners

### ISSUE THREAD

**Issue by dptaf** [Azure/login#369]
<img width="1126" alt="image" src="https://github.com/Azure/login/assets/104381982/dcceb511-7562-4f73-929a-766a9e33e5c6">

We have workflows that run on the github dedicated runners. When running on those runners we get the following log:

Error: undefined. Please make sure to give write permissions to id-token in the workflow.

The workflow still continues with the rest of the actions, so it doesn't seem like it's a fatal error. We've noticed that if we just use the ubuntu-latest runners, we don't get an error.

**Comment by YanaXu** [comment]
Hi @dptaf ，

Did you put the below part before your job in the workflow file?
```yaml
permissions:
      id-token: write
      contents: read
```

**Comment by dptaf** [comment]
hi @YanaXu -- yes we have the permissions block in there. and to note, this only shows when running on the github [large runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners). if we use a regular ubuntu agent, we don't see the error. and to re-iterate this doesn't seem to block our deployments to azure, just produces that error log

**Comment by YanaXu** [comment]
Hi @dptaf , I suspect the GitHub large runners env you're using blocks the message from your runner to GitHub Service. Could you run below workflow file and provide me the run log? Please note, `runs-on: ubuntu-latest` may need to be updated to the right value.

```yaml
name: Test getIDToken
on: [push, workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs: 
  test-getIDToken:
    runs-on: ubuntu-latest
    steps:

    - name: GetToken
      continue-on-error: true
      uses: actions/github-script@v3
      with:
        script: |
          const idToken = await core.getIDToken('api://AzureADTokenExchange');
          idToken == null ? console.log("idToken is null or undefined") : console.log("idToken is fine");
          let tokenPayload = idToken.split('.')[1];
          tokenPayload == null ? console.log("tokenPayload is null or undefined") : console.log("tokenPayload is fine");
          let bufferObj = Buffer.from(tokenPayload, "base64");
          bufferObj == null ? console.log("bufferObj is null or undefined") : console.log("bufferObj is fine");
          let decodedPayload = JSON.parse(bufferObj.toString("utf8"));
          decodedPayload == null ? console.log("decodedPayload is null or undefined") : console.log("decodedPayload is fine")
          let iss = decodedPayload['iss'];
          iss == null ? console.log("iss is null or undefined") : console.log("iss is fine")
          let sub = decodedPayload['sub'];
          sub == null ? console.log("sub is null or undefined") : console.log("sub is fine")
```
