### ISSUE TITLE
v1.5.1 breaks login with creds

### ISSUE THREAD

**Issue by alexkunde** [Azure/login#381]
Hi, we are using

```yaml
- name: Azure login
        uses: azure/login@v1.5.1
        with:
          creds: ${{ secrets.SECRET_VALUE }}
```
This works fine with v1.5.0.
When I updated to 1.5.1 the following error occured.

```
Run azure/login@v1.5.1
  with:
    enable-AzPSSession: false
    environment: azurecloud
    allow-no-subscriptions: false
    audience: api://AzureADTokenExchange
    auth-type: SERVICE_PRINCIPAL
Error: Login failed with Error: Using auth-type: SERVICE_PRINCIPAL. Not all values are present. Ensure 'client-id' and 'tenant-id' are supplied.. Make sure 'az' is installed on the runner. If 'enable-AzPSSession' is true, make sure 'pwsh' is installed on the runner together with Azure PowerShell module. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.
```

This leads to 1.5.1 being a breaking change for us. Can you please have a look if this is intended?

Best,
Alex
