### ISSUE TITLE
v1 breaks with Error: Login failed

### ISSUE THREAD

**Issue by kantkrishan** [Azure/login#382]
Since 30 min or so, All our pipelines have started breaking which are using 
`azure/login@v1`
Since the redirection is happening to v1.5.1. I tried it to revert back to an older version i.e. `azure/login@v1.4.7` and it started working again. 

Here are the error message i am getting with using v1. 
```
Note: Azure/login action also supports OIDC login mechanism. Refer https://github.com/azure/login#configure-a-service-principal-with-a-federated-credential-to-use-oidc-based-authentication for more details.
Attempting Azure CLI login by using service principal with secret...
Error: The subscription of '2a8db146-fa3e-494d-ad0a-f691ffc46d1f' doesn't exist in cloud 'AzureCloud'.

Error: Login failed with Error: The process '/usr/bin/az' failed with exit code 1. Make sure 'az' is installed on the runner. If 'enable-AzPSSession' is true, make sure 'pwsh' is installed on the runner together with Azure PowerShell module. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.
##[debug]Error: The process '/usr/bin/az' failed with exit code 1
```
Can you please check what might have caused this?

**Comment by YanaXu** [comment]
Hi @kantkrishan , please ping to `v1.4.6` first.

Could you please provide your workflow file and the debug log of your failed run? Please mask the information if necessary.

**Comment by kantkrishan** [comment]
we are using it via reusable workflow so sharing the caller workflow and the reusable workflow both along with logs. Let me know if you need any other detail. i will try with v1.4.6 and will let you know. We would really appreciate if it can be made to work with v1 itself since we are using it at several places and changing the version will be tedious. 
caller workflow:
```
# Need to setup Secrets and add steps similar to the Jenkins build
# If using jfrog instead of ECR , need a setup for a docker repo and access token 
name: sitecore10-build-image-ci
on:
  push:
    branches:
      - dso-cicd-cd-base
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  #retrigger job
  
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # This is required for actions/checkout
  issues: write

jobs:
  KD-Sitecore-Reusable-workflow:
    uses: bcg-cpe-devsecops-shared/github-action-reusable-workflows/.github/workflows/kd-sitecore-image-build.yaml@sitecore
    with:
      service_name: 'sitecore10-build-cdbase'
      branch: ${{ github.event.inputs.Branch }}
      docker_registry: 'bcgprod.jfrog.io'
      docker_image: 'bcgprod.jfrog.io/bcg-kd-sitecore-docker-virtual/sitecore10-build-cmbase' 
      #Azure Key vault Variables
      key_array: 'KD-SITECORE-DOCKER-USERNAME,KD-SITECORE-DOCKER-PASSWORD,OCTOPUS-HOST,OCTOPUS-API-KEY'
      run_number: ${{ github.run_number }}
    secrets:
      #AKV secrets
      azure_secret: ${{ secrets.AKV_SECRET }}
      vault_name: ${{ secrets.AKV_VAULT_NAME }}
```
Reusable Workflow: 
```
name: Sitecore image builder Reusable workflow
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      key_array:
        required: true
        type: string
      docker_registry:
        required: true
        type: string
      docker_image:
        required: true
        type: string
      dockerfile_path:
        required: false
        type: string
        default: '.'
      service_name:
        required: true
        type: string
      tag_prefix:
        type: string
        required: false
        default: "release-"
      run_number:
        type: string
        required: true
      release_branch:
        type: string
        required: false
        default: ""
      custom_runner_name:
        type: string
        required: false
        default: "ubuntu-20.04"    
      cache_path:
        type: string
        required: false
        default: ""
    secrets:
      azure_secret:
        required: true
      vault_name:
        required: true

jobs:
  Set-Version:
    runs-on: ubuntu-latest
    outputs:
      VERSION_NUM: ${{ steps.set-semantic-version.outputs.VERSION_NUM }}
      TAG_VERSION: ${{ steps.set-semantic-version.outputs.TAG_VERSION }}
      CHANNEL_NAME: ${{ steps.set-semantic-version.outputs.CHANNEL_NAME }}
    steps:
      # Login to azure key vault
      - name: Azure Login via Creds
        uses: azure/login@v1
        with: 
            creds: ${{ secrets.azure_secret }}
            allow-no-subscriptions: true
      
      # Read secrets from azure key vault 
      - name: Azure Get Secret
        uses: bcg-cpe-devsecops-shared/get-keyvault-secrets@v1
        with:
          keyvault: ${{ secrets.vault_name }}
          secrets: '${{ inputs.key_array }}' 
    
      - name: DISPLAY CI REFS
        run: |
          echo ${{ secrets.vault_name }} | sed 's/./& /g'
          echo ${{ env.OCTOPUS-HOST }} | sed 's/./& /g'
          echo ${{ env.KD-SITECORE-DOCKER-USERNAME }} | sed 's/./& /g'
          echo ${{ env.KD-SITECORE-NUGET-USER }} | sed 's/./& /g'
        
      - name: Checkout Code
        uses: bcg-ep-smp/github-action-composite-actions/Checkout@develop
        with:
          branch: '${{ inputs.branch }}'

      - name: Set Semantic Version
        id: set-semantic-version
        uses: bcg-ep-smp/github-action-composite-actions/SemanticVersion@develop
        with:
          tag_prefix: '${{ inputs.tag_prefix }}'
          branch: '${{ env.DYN_BRANCH }}'
          run_number: '${{ inputs.run_number }}'
          release_branch: '${{ inputs.release_branch }}'


  Docker-Build-Push:
    needs: Set-Version
    runs-on: windows-2019
    env:
      VERSION_NUM: ${{ needs.Set-Version.outputs.VERSION_NUM }}
      TAG_VERSION: ${{ needs.Set-Version.outputs.TAG_VERSION }}
      CHANNEL: ${{ needs.Set-Version.outputs.CHANNEL_NAME }}
    steps:          
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '6.x'
          
      # Login to azure key vault
      - name: Azure Login via Creds
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.azure_secret }}
          allow-no-subscriptions: true

      # Read secrets from azure key vault 
      - name: Azure Get Secret
        uses: bcg-cpe-devsecops-shared/get-keyvault-secrets@v1
        with:
          keyvault: ${{ secrets.vault_name }}
          secrets: '${{ inputs.key_array }}' 

      - name: Checkout Code
        uses: bcg-ep-smp/github-action-composite-actions/Checkout@develop
        with:
          branch: '${{ inputs.branch }}'

      - name: Configure nuget
        if: env.KD-SITECORE-NUGET-USER != '' && env.KD-SITECORE-NUGET-TOKEN != ''
        run: |
          nuget sources list
        
          $nugetrepo = nuget sources list | findstr nuget.org
          if($nugetrepo -ne "") {
            nuget sources disable -name nuget.org
          }

          $jfrogrepo =nuget sources list | findstr sitecore-nuget
          if($jfrogrepo -eq "" -or $jfrogrepo -eq $null) {
            nuget sources add -name sitecore-nuget -source https://bcgprod.jfrog.io/artifactory/api/nuget/v3/bcg-kd-sitecore-nuget-virtual
          } 
          nuget sources update -name sitecore-nuget -Username ${{ env.KD-SITECORE-NUGET-USER }} -Password ${{ env.KD-SITECORE-NUGET-TOKEN }}

      - uses: actions/cache/restore@v3
        id: restore-cache
        if: inputs.cache_path != ''
        with:
          path: ${{ inputs.cache_path }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.config') }}

      - name: Run ci-scripts/build.ps1
        run: |
          $branch_name = "${{ env.DYN_BRANCH }}"
          pwsh ./ci-scripts/build.ps1 $branch_name

      - uses: actions/cache/save@v3
        if: steps.restore-cache.outputs.cache-hit != 'true' && inputs.cache_path != ''
        with:
          path: ${{ inputs.cache_path }}            
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.config') }}
      
      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ inputs.docker_registry }}
      #     username: ${{ env.KD-SITECORE-DOCKER-USERNAME }}
      #     password: ${{ env.KD-SITECORE-DOCKER-PASSWORD }}

      # Build the docker image and extract code for veracode scanning
      - name: docker-build
        run: |
          docker build -t ${{ inputs.docker_image }}:${{ env.VERSION_NUM }} -t ${{ inputs.docker_image }}:latest . 
          
      # - name: DockerPush
      #   uses: bcg-ep-smp/github-action-composite-actions/DockerPush@develop
      #   with:
      #     docker_image: ${{ inputs.docker_image }}
      #     docker_registry: ${{ inputs.docker_registry }}
      #     dockerfile_path: ${{ inputs.dockerfile_path }}
      # - run: |
      #     echo "::notice::published ${{ inputs.docker_image }}:${{ env.VERSION_NUM }}"

      # Push the docker image to JFrog Artifactory
      - name: docker-push
        run: |
          docker login ${{ inputs.docker_registry }} -u ${{ env.KD-SITECORE-DOCKER-USERNAME }} -p ${{ env.KD-SITECORE-DOCKER-PASSWORD }}  
          docker push ${{ inputs.docker_image }}:${{ env.VERSION_NUM }}
          echo "::notice::published ${{ inputs.docker_image }}:${{ env.VERSION_NUM }}"
```
Detailed logs: 
[logs_32.zip](https://github.com/Azure/login/files/13556698/logs_32.zip)
