### ISSUE TITLE
📢 Azure/login v1.6.0 Pre-Release Announcement

### ISSUE THREAD

**Issue by MoChilia** [Azure/login#399]
**Azure/login v1.6.0** will be officially released on **Jan 16, 2024**.  At that time, **`v1` will be pointed to `v1.6.0`**.

🚀   **Preview Available**
A preview for Azure/login v1.6.0 is now ready to use. Update the version to `azure/login@v1.6.0` to explore the new feature. Test it out and ensure your workflow is compatible with this release. The following is a sample workflow.
```yaml
    - name: Azure Login
      uses: azure/login@v1.6.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
```
We invite you to share your suggestions and any potential issues in this issue thread. Your insights play a crucial role in refining our product.

👀  **What’s new in Azure/login v1.6.0?**
Add `pre:` and `post:` action for cleaning up (#384)
