### ISSUE TITLE
Pre Azure Login and Post Azure login failing

### ISSUE THREAD

**Issue by wulfnb** [Azure/login#405]
In GitHub actions, I'm using Azure Login.

But 4 hours ago its getting new jobs getting added **Pre Azure Login** and **Post Azure login** and its failing.

```
    - name: Azure login
      uses: Azure/login@v1
      with:
        creds: 
```

<img width="1305" alt="Screenshot 2024-01-16 at 6 24 43 PM" src="https://github.com/Azure/login/assets/46603705/868e4702-0af4-46ff-9100-61fff6562e64">
<img width="1305" alt="Screenshot 2024-01-16 at 6 28 16 PM" src="https://github.com/Azure/login/assets/46603705/a59f347e-c154-410d-aa28-a8f05b625d03">
