### ISSUE TITLE
Possible to update the Versioning of modules?

### ISSUE THREAD

**Issue by PedramRjoo** [Azure/login#410]
When we run, we get 
"WARNING: You're using Az version 9.3.0. The latest version of Az is [11]"
Is there a way to update the versioning, in our yaml file or to check for another versioning of azure/login@v1?
Same for v1.6.0

```
deploy:
    runs-on: ubuntu-latest
.......

 - name: Azure login
        uses: azure/login@v1.6.0
        with:
          client-id: "XXXX"
          tenant-id: "XXXX"
          enable-AzPSSession: true
          allow-no-subscriptions: true
```

```
Run azure/login@v1
Clearing azure cli accounts from the local cache.
/usr/bin/az account clear
{
  Result: '/usr/share/az_9.3.0/Az.Accounts/2.15.0/Az.Accounts.psd1',
  Success: true
}
Clearing azure powershell accounts from the local cache.
/usr/bin/pwsh -Command Clear-AzContext -Scope Process
/usr/bin/pwsh -Command Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
WARNING: You're using Az version 9.3.0. The latest version of Az is [11](https://github.com/Azure/login/actions/runs/7613112857/job/20732255168#step:4:12).2.0. Upgrade your Az modules using the following commands:
  Update-Module Az -WhatIf    -- Simulate updating your Az modules.
  Update-Module Az            -- Update your Az modules.
There will be breaking changes from 9.3.0 to 11.2.0. Open https://go.microsoft.com/fwlink/?linkid=224[13](https://github.com/Azure/login/actions/runs/7613112857/job/20732255168#step:4:14)73 and check the details.
```

Might be easy fix, but not sure
