### ISSUE TITLE
Not able to use azure/login@v2 and azure/CLI@v2 in one job

### ISSUE THREAD

**Issue by wenwenchenbosch** [Azure/login#429]
I am currently set up my github action to do azure deployment":

```
jobs:
    build:
        runs-on: [self-hosted] 
        #container:
        #    image: mcr.microsoft.com/azure-cli:latest
        steps:
        - name: Login to Azure
          uses: azure/login@v2
          with:
                creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
        - name: Deploy ARM Template
          uses: azure/CLI@v2
          with:
                azcliversion: latest
                inlineScript: |
                    az account show
```

but it does not work for me: The problem is, azure/login required 'az' as tool to be installed on the runner
https://github.com/Azure/login/blob/e9468bad0a1e2a5863b25f77ea9b6ce0d19f5e41/src/Cli/AzureCliLogin.ts#L19

but azure/Cli required 'docker', see
https://github.com/Azure/cli/blob/99c7fe7a21b1dbe885695e092bf8451d20bac9c0/src/main.ts#L123

If I use `image: mcr.microsoft.com/azure-cli:latest` to run the job, I get error: "Error: Unable to locate executable file: docker". If I let the job run directly on my runner, I get error: "Error: Unable to locate executable file: az".

The question is: Why both action work in different way?
