### ISSUE TITLE
Unable to modify network-rule

### ISSUE THREAD

**Issue by jjescobaruni** [Azure/login#44]
Hi!
I am posting this issue because I am getting the following error since I added into my working Github action workflow an additional step to modify the network-rule of my storage account before uploading the files in order to allow the runner IP:
```
There is no credential provided in your command and environment, we will query account key for your storage account. 
Please provide --connection-string, --account-key or --sas-token as credential, or use `--auth-mode login` if you have required RBAC roles in your command. For more information about RBAC roles in storage, you can see https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-cli. 
```
So my workflow was previously like this:
```
- name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_TEST }}
      - name: Update build in Storage Account
        run: |
          az storage blob delete-batch -s \$web --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME_TEST }}
          az storage blob upload-batch -s $GITHUB_WORKSPACE/build -d \$web --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME_TEST }}
```

And now I just have added the first following step:
```
- name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_TEST }}
      - name: Update build in Storage Account
        run: |
          az storage account network-rule add --resource-group "MyResourceGroup" --account-name "MyAccountName" --ip-address "${{ steps.runner.outputs.runner_ip }}"
          az storage blob delete-batch -s \$web --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME_TEST }}
          az storage blob upload-batch -s $GITHUB_WORKSPACE/build -d \$web --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME_TEST }}
```

I am aware that this might be because of the rules in my network, but the weird thing is that the IP is added to it before failing.

Any ideas regarding this issue?
Thanks!
