### ISSUE TITLE
Github Workflow Failing at Azure login

### ISSUE THREAD

**Issue by Logeswari25** [Azure/login#447]
While deploying the pipeline I am getting below error.

![github_error](https://github.com/Azure/login/assets/149675131/d7237ad0-6672-4725-bdb5-aef016cc2edf)

I'm not sure why I'm encountering this issue. Any help or guidance would be greatly appreciated.

Here is my work flow:

![Github_workflow](https://github.com/Azure/login/assets/149675131/cf10c9e5-2e83-4c63-8241-ea910e67268c)

**Comment by YanaXu** [comment]
Hi @Logeswari25, please follow this example:
```yaml
  - uses: azure/login@v2
    with:
      creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
```

And please consider using OIDC instead of SP+secret. Check [here](https://github.com/Azure/login?tab=readme-ov-file#login-with-openid-connect-oidc-recommended).
