### ISSUE TITLE
Azure PowerShell Login fails with SyntaxError

### ISSUE THREAD

**Issue by devopsjesus** [Azure/login#451]
Azure Login steps on GitHub-hosted runners are now failing PowerShell logins (enable-AzPSSession attribute set to 'true') with error:

`Error Login failed with SyntaxError: Unexpected token 'R', "Retrieving"... is not valid JSON. Double check in the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.`

The output of the step includes a reference to Az.Accounts PowerShell module version 3.0.0 which was released roughly a week ago. Upon investigation, this new version of the module will retrieve a list of subscriptions the authenticated user has access to, with a message beginning with "Retrieving...". This points to a possible issue with this new behavior of the new version of the Az.Accounts.

Downgrading to version 2.19.0 of Az.Accounts prior to the Azure Login step allows for successful authentication and step completion.

**Comment by matejskubic** [comment]
> Downgrading to version 2.19.0 of Az.Accounts prior to the Azure Login step allows for successful authentication and step completion.

Workaround 

```yaml
    - name: Douwgrade Az.Accounts workaround
      uses: Azure/powershell@v2
      with:
        azPSVersion: latest
        inlineScript: |
          Install-Module -Name Az.Accounts -RequiredVersion 2.19.0 -Force

```
