### ISSUE TITLE
Workflow claims no matching federated identity record found for presented assertion subject on pull requests

### ISSUE THREAD

**Issue by raveheart1** [Azure/login#461]
# Terraform Error: Failed to Retrieve Workspaces Due to Invalid Client Credentials

## Description
This error occurs when attempting to retrieve keys for the Storage Account `storageAccountName` in Azure. The error message indicates an issue with the federated identity credentials used for authentication.

## Error Message
```
Error: Failed to get existing workspaces: Error retrieving keys for Storage Account "storageAccountName": autorest/Client#Do: Preparing request failed: StatusCode=0 -- Original Error: clientCredentialsToken: received HTTP status 401 with response: {"error":"invalid_client","error_description":"AADSTS700213: No matching federated identity record found for presented assertion subject 'repo:orgName/repoName:pull_request'. Please check your federated identity credential Subject, Audience and Issuer against the presented assertion. https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation Trace ID: traceId Correlation ID: correlationId Timestamp: 2024-06-13 15:40:46Z","error_codes":[700213],"timestamp":"2024-06-13 15:40:46Z","trace_id":"traceId","correlation_id":"correlationId"}
```

## Cause
The error `AADSTS700213` indicates that Azure Active Directory (AAD) could not find a matching federated identity record for the presented assertion. This typically means there is a mismatch between the federated identity credential and the presented assertion in terms of Subject, Audience, and Issuer.

## Confirmations
- There **is** a federated identity for the presented assertion.
- The app registration has the necessary rights to access the storage account.
- The workflow can run successfully if ran directly from the main branch because the federated identity for our repo's main branch already exists.

## References
- [Azure AD Workload Identity Federation Documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation)
- [Troubleshooting Azure AD Application Authentication](https://docs.microsoft.com/en-us/azure/active-directory/develop/troubleshoot-application-authentication)

## Additional Information
Pull requests fail on our terraform init step in the workflow. Below is some of the code we are using:
     
```
     - name: Downgrade Az.Accounts workaround
        uses: Azure/powershell@v2
        with:
          azPSVersion: latest
          inlineScript: |
            Install-Module -Name Az.Accounts -RequiredVersion 2.19.0 -Force
      
      - name: Login to Azure US Gov Cloud with CLI
        uses: azure/login@v2.1.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: 'AzureUSGovernment'
          enable-AzPSSession: true
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Init
        id: init
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      - name: Terraform Plan
        run: terraform plan -no-color -out tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: true
```

Any help is appreciated, not sure if this is a bug with azure or a misconfiguration
