### ISSUE TITLE
Deployment Failing

### ISSUE THREAD

**Issue by sirajahmadzai** [Azure/login#464]
Hello,

I am running into this error when following one of Microsoft Learn's exercises:

```
Run azure/login@v1
Running Azure CLI Login.
/usr/bin/az cloud set -n azurecloud
Done setting cloud: "azurecloud"
Federated token details:
 issuer - https://token.actions.githubusercontent.com
 subject claim - repo:sirajahmadzai/mslearn-advocates.azure-functions-and-signalr:environment:Production
Attempting Azure CLI login by using OIDC...
Error: AADSTS700213: No matching federated identity record found for presented assertion subject 'repo:sirajahmadzai/mslearn-advocates.azure-functions-and-signalr:environment:Production'. Please check your federated identity credential Subject, Audience and Issuer against the presented assertion. https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation Trace ID: 9[15](https://github.com/sirajahmadzai/mslearn-advocates.azure-functions-and-signalr/actions/runs/9589306601/job/26443564754#step:5:16)d52ba-4181-49ad-b614-c8321c3a4400 Correlation ID: e42f5e57-bac2-4c33-86e3-c330510e0d18 Timestamp: 2024-06-20 00:[16](https://github.com/sirajahmadzai/mslearn-advocates.azure-functions-and-signalr/actions/runs/9589306601/job/26443564754#step:5:17):43Z

Error: Interactive authentication is needed. Please run:
az login

Error: Login failed with Error: The process '/usr/bin/az' failed with exit code 1. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.
```

I am following this exercise: 

[https://learn.microsoft.com/en-us/training/modules/automatic-update-of-a-webapp-using-azure-functions-and-signalr/5-exercise-enable-automatic-updates-in-a-web-app-using-signalr](url)

I am able to successfully build but deployment fails.

**Comment by YanaXu** [comment]
Hi @sirajahmadzai , please refer to the guide: [Login With OpenID Connect (OIDC) [Recommended]](https://github.com/Azure/login?tab=readme-ov-file#login-with-openid-connect-oidc-recommended).
And your workflow failes because of this step [Configure a federated identity credential on an service principal](https://learn.microsoft.com/entra/workload-id/workload-identity-federation-create-trust?pivots=identity-wif-apps-methods-azp#github-actions).

Please double confirm you have configured the correct federated credential for "repo:sirajahmadzai/mslearn-advocates.azure-functions-and-signalr:environment:Production". 
![image](https://github.com/Azure/login/assets/12843157/29866994-4558-48ed-ad54-411f7faac991)

**Comment by SatriaPriambada** [comment]
Hi I also faced the same issue with CD from Azure Function

I want to follow up is there any way to actually solve this problem? I can't seem to follow up the tutorial on [Configure a federated identity credential on an service principal](https://learn.microsoft.com/entra/workload-id/workload-identity-federation-create-trust?pivots=identity-wif-apps-methods-azp#github-actions).
```
To add a federated identity for a GitHub action, follow these steps:

Find your app registration in the Microsoft Entra admin center app registration experience. Select Certificates & secrets in the left navigation pane, select the Federation credentials tab, and select Add credentials.

```
I can enter https://entra.microsoft.com/ but there's nothing about App Registration of my Azure Function, No Certificate & Secrets in the left navigation tab, and no Add Federation credentials

additional information: 
I can deploy my code manually via the web and using Visual Studio code
It's just the Azure/login in Github action that seems to have problem with deployment

I checked my Github Repo Secret and I can see that Azure Function add the secret there

**Comment by YanaXu** [comment]
Hi @SatriaPriambada , please check the guide. First, you have to create a SP and add the right role assignment.  Second, you can add a federation credential. Third, you can use it in your Azure Login Action. Please kinldy click the 2 links and you will see the configuration pages for reference.
![image](https://github.com/Azure/login/assets/12843157/88787b10-6c89-498e-9432-6889a6373fd6)

**Comment by SatriaPriambada** [comment]
Hi @YanaXu thanks for the quick reply, 

Unfortunately I still didn't get your instruction since it's basically just a repeat of what you've said before...
I have a CD pipeline from Azure Function -> Deployment -> Distribution Center auto generated github action
![image](https://github.com/Azure/login/assets/9639954/a0e0e299-0e4e-4da2-a639-d5557f0507ce)

However on azure/login steps it failed with this same error in this thread

I have added the federation credential that you mentioned but still get the error
```
Federated token details:
 issuer - https://token.actions.githubusercontent.com/
 subject claim - repo:EndeavourEnergy/GigaGrid_Cert_Generator:environment:Production
Attempting Azure CLI login by using OIDC...
Error: AADSTS700[21](https://github.com/EndeavourEnergy/GigaGrid_Cert_Generator/actions/runs/9685718530/job/26764556663#step:5:22)3: No matching federated identity record found for presented assertion subject 'repo:EndeavourEnergy/GigaGrid_Cert_Generator:environment:Production'. Please check your federated identity credential Subject, Audience and Issuer against the presented assertion
```
This is my Entra view that said that subject claim - repo:EndeavourEnergy/GigaGrid_Cert_Generator:environment:Production
has existed
![image](https://github.com/Azure/login/assets/9639954/74d263a4-3fce-43a1-8ac6-9e8228136a51)

Is there a missing step? Like having to link my Azure Function to Entra or something not said in the tutorial?

Thanks and have a great day!

**Comment by sirajahmadzai** [comment]
It also doesn't work for me, I am not sure why they haven't put clear instructions in the Microsoft Learn activity for this exercise, now I am getting this error: 

`Run azure/login@v1
Running Azure CLI Login.
/usr/bin/az cloud set -n azurecloud
Done setting cloud: "azurecloud"
Federated token details:
 issuer - https://token.actions.githubusercontent.com/
 subject claim - repo:sirajahmadzai/mslearn-advocates.azure-functions-and-signalr:environment:Production
Attempting Azure CLI login by using OIDC...
Error: No subscriptions found for ***.

Error: Login failed with Error: The process '/usr/bin/az' failed with exit code 1. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.`

The exercise I am trying to complete is: https://www.coursera.org/learn/create-serverless-applications/supplement/yBhoa/exercise-enable-automatic-updates-in-a-web-application-using-signalr-service

**Comment by YanaXu** [comment]
> Hi @YanaXu thanks for the quick reply,
> 
> Unfortunately I still didn't get your instruction since it's basically just a repeat of what you've said before... I have a CD pipeline from Azure Function -> Deployment -> Distribution Center auto generated github action ![image](https://private-user-images.githubusercontent.com/9639954/343800234-a0e0e299-0e4e-4da2-a639-d5557f0507ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTY2NTIsIm5iZiI6MTcxOTgxNjM1MiwicGF0aCI6Ii85NjM5OTU0LzM0MzgwMDIzNC1hMGUwZTI5OS0wZTRlLTRkYTItYTYzOS1kNTU1N2YwNTA3Y2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDFUMDY0NTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjU3YmY2OWQzZmE5NmVkMDNlOGY0OTQ5N2MzODVhZDkxMWM1ZWQ2N2E4NDk2ZGMyMWFjODVkY2JlYTY0YzljMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5gzsBE54HDyFMDQUkHI-Xp0qLYbJrqG4CrgNzQ8VZXQ)
> 
> However on azure/login steps it failed with this same error in this thread
> 
> I have added the federation credential that you mentioned but still get the error
> 
> ```
> Federated token details:
>  issuer - https://token.actions.githubusercontent.com/
>  subject claim - repo:EndeavourEnergy/GigaGrid_Cert_Generator:environment:Production
> Attempting Azure CLI login by using OIDC...
> Error: AADSTS700[21](https://github.com/EndeavourEnergy/GigaGrid_Cert_Generator/actions/runs/9685718530/job/26764556663#step:5:22)3: No matching federated identity record found for presented assertion subject 'repo:EndeavourEnergy/GigaGrid_Cert_Generator:environment:Production'. Please check your federated identity credential Subject, Audience and Issuer against the presented assertion
> ```
> 
> This is my Entra view that said that subject claim - repo:EndeavourEnergy/GigaGrid_Cert_Generator:environment:Production has existed ![image](https://private-user-images.githubusercontent.com/9639954/343816050-74d263a4-3fce-43a1-8ac6-9e8228136a51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTY2NTIsIm5iZiI6MTcxOTgxNjM1MiwicGF0aCI6Ii85NjM5OTU0LzM0MzgxNjA1MC03NGQyNjNhNC0zZmNlLTQzYTEtOGFjNi05ZTgyMjgxMzZhNTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDFUMDY0NTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2MxODliOGI3MGM4ZTJkNjYyYTE3ZDY3OTU1MWE3MjQ3MmM4ZjY3ZWE3NzI3YzBjODkyZjlhMjdmYmUzMGU1MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hbs-jv_Z1gNMTFK5WwuEbXc25ckmg3HPOuqQ034yXhY)
> 
> Is there a missing step? Like having to link my Azure Function to Entra or something not said in the tutorial?
> 
> Thanks and have a great day!

Hi @SatriaPriambada,
Could you share the workflow file and Service Principal page? The error means the SP you used in the GitHub Action do not have the federated credential. But the page of the federated credential you shared in your comment seems correct. Could you double check if you're using it for Azure Login Action?
And please do use the latest Azure Login Action, which is **v2**.

**Comment by YanaXu** [comment]
> It also doesn't work for me, I am not sure why they haven't put clear instructions in the Microsoft Learn activity for this exercise, now I am getting this error:
> 
> `Run azure/login@v1 Running Azure CLI Login. /usr/bin/az cloud set -n azurecloud Done setting cloud: "azurecloud" Federated token details: issuer - https://token.actions.githubusercontent.com/ subject claim - repo:sirajahmadzai/mslearn-advocates.azure-functions-and-signalr:environment:Production Attempting Azure CLI login by using OIDC... Error: No subscriptions found for ***.
> 
> Error: Login failed with Error: The process '/usr/bin/az' failed with exit code 1. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.`
> 
> The exercise I am trying to complete is: https://www.coursera.org/learn/create-serverless-applications/supplement/yBhoa/exercise-enable-automatic-updates-in-a-web-application-using-signalr-service

Hi @sirajahmadzai,

Could you please also share your workflow file, the SP Federated credential configuration page? Let's see where is not well configured.

**Comment by Goldziher** [comment]
same issue after generating a workflow for azure function apps from the azure portal. There seems to be a bug on the azure function app generation layer which doesn't setup all the requirements automatically. Very annoying.

**Comment by YanaXu** [comment]
> same issue after generating a workflow for azure function apps from the azure portal. There seems to be a bug on the azure function app generation layer which doesn't setup all the requirements automatically. Very annoying.

Hi @Goldziher , could you help me to check the SP used in your workflow and the SP Federated credential configuration. If it's related to the Azure Function, I can reach out to them for further analysis on this.

**Comment by Goldziher** [comment]
There was no service principal. The function app deployment wizard now creates a managed identity. It also populates the service, client and tenant id correctly in github. 

I cannot help further since I already deleted this and created a service principal manually instead. I would suspect though that the github action v2 does not work correctly with managed identities.

**Comment by YanaXu** [comment]
Hi @Goldziher, you meam a user managed identity, right? It's similar as SP in OIDC login. If you can reproduce it, please help me collect the user managed identity information & the workflow & the user managed identity federated credential configuration. Thanks a lot!

**Comment by sirajahmadzai** [comment]
@YanaXu here is my workflow file: 

https://github.com/sirajahmadzai/mslearn-advocates.azure-functions-and-signalr/blob/main/.github/workflows/main_api-siraj.yml

Here is my SP Federated Credential page: 

![image](https://github.com/Azure/login/assets/29950027/49fb205e-d309-47f4-9ede-88b9f03082c4)

Mind you that the original exercise does not mention any SP Federated Credential needing to be setup. Could you please have a look at the exercise I am trying to complete: 

https://learn.microsoft.com/en-us/training/modules/automatic-update-of-a-webapp-using-azure-functions-and-signalr/5-exercise-enable-automatic-updates-in-a-web-app-using-signalr

**Comment by YanaXu** [comment]
Thanks @sirajahmadzai. Could you take the following steps and see if it works:
- In your [workflow file](https://github.com/sirajahmadzai/mslearn-advocates.azure-functions-and-signalr/blob/main/.github/workflows/main_api-siraj.yml), replace "uses: azure/login@v1" to "uses: azure/login@v2".
- Open [your github repo environment configuration page](https://github.com/sirajahmadzai/mslearn-advocates.azure-functions-and-signalr/settings/environments) and see if there is a "Production" environment and it contains all necessary secrets: **AZUREAPPSERVICE_CLIENTID_EBEF9E463BB8449BA5F1BD752A408B69**， **AZUREAPPSERVICE_TENANTID_19176ABCFC7E4E47BDB3FD6E9CF43944**， **AZUREAPPSERVICE_SUBSCRIPTIONID_3A761AB7C5C449DEAAE12F54EC84CDD3**.
  - If the secrets are there, please edit them, copy the values from your SP page to the secrets. (the tenant id, subscription id, sp client id)
  - If the secrets are not there, please create 3 new secrets with the name and the correct values.
- Run the workflow again. 

Please reply me with your findings. Thanks!

**Comment by sirajahmadzai** [comment]
@YanaXu I am still getting the same error after making the changes you requested, I re-built the project and re-deployed, the build succeeds but the deployment is failing. Also I still see azure/login@v1 being referenced even though I changed it to v2: 

`Run azure/login@v1
Running Azure CLI Login.
/usr/bin/az cloud set -n azurecloud
Done setting cloud: "azurecloud"
Federated token details:
 issuer - https://token.actions.githubusercontent.com/
 subject claim - repo:sirajahmadzai/mslearn-advocates.azure-functions-and-signalr:environment:Production
Attempting Azure CLI login by using OIDC...
Error: No subscriptions found for ***.

Error: Login failed with Error: The process '/usr/bin/az' failed with exit code 1. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.`

**Comment by YanaXu** [comment]
Hi @sirajahmadzai , it seems it's not an issue of Azure Login Action. Could you raise a issue to the guide: https://learn.microsoft.com/en-us/training/modules/automatic-update-of-a-webapp-using-azure-functions-and-signalr/5-exercise-enable-automatic-updates-in-a-web-app-using-signalr ?
![image](https://github.com/Azure/login/assets/12843157/4fa4ded4-9e43-4d05-9344-005b0ae8d670)

**Comment by SatriaPriambada** [comment]
> Could you share the workflow file and Service Principal page? The error means the SP you used in the GitHub Action do not have the federated credential. But the page of the federated credential you shared in your comment seems correct. Could you double check if you're using it for Azure Login Action?

Hi @YanaXu ,

Thanks for your reply and your help

The workflow file:
```
# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - provisionmanufacture

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          npm run test --if-present
          popd

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0E7D9513B6144F44A1298EC33518C78A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E7A9F92BD90648C195CF8C2F6F50CA42 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5C8AA0BFC20B4527BA6F36B219868C56 }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'provisionmanufacture'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
```
I've checked and have the credentials as shown here:
![image](https://github.com/Azure/login/assets/9639954/04f47433-e36f-47a9-bb8f-ed3325f05783)

My Service Principal Page:
![image](https://github.com/Azure/login/assets/9639954/2a881b85-31eb-47f4-afa3-069e31600d0d)


All of this is autogenerated by Azure Function click. 
I've followed your instructions and added Federated Credentials and upgrade from `azure/login/v1` to v2 and I still have to manually deploy my function from VS Code
It's been more than a week now, if it still doesn't work would you mind escalating the ticket from question to an actual misconfiguration issues from Azure Function or bug in Azure Login?

Thanks and have a great day!
