### ISSUE TITLE
`azure/login@v2` generating unexpected subject during login.

### ISSUE THREAD

**Issue by Chrisell** [Azure/login#468]
While using the login as follows:
```
      - name: Log in to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
```
an unexpected subject in the OIDC token is being used:
```
Federated token details:
 issuer - https://token.actions.githubusercontent.com/
 subject claim - repository_owner:my_org:repository_visibility:internal:workflow:manual-deployment
```

I've compared this to another repository that is generating the correct subject, along with the federated credentials within Azure, and can not determine any difference between the two. I was also unable to find any similar issues or topics online. Am I missing something obvious here?
