### ISSUE TITLE
AADSTS700213: No matching federated identity record found for presented assertion subject

### ISSUE THREAD

**Issue by cmckeen** [Azure/login#482]
Hello,

I'm attempting to run the login action like the following:

```
      - name: 'Azure CLI login'
        uses: azure/login@v2.1.0
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: ${{ env.AZURE_SUBSCRIPTION_ID == '' }}
```

This results in the following workflow output:

```
Run azure/login@v2.1.0
  with:
    client-id: af3110ba-0ba9-4412-b1a0-59f50b7e9273
    tenant-id: 4ecd6548-e33b-4b9d-9986-bd3c22986c6
    subscription-id: 868ab87f-fc57-46b2-8815-9b80a74b8922
    allow-no-subscriptions: false
    enable-AzPSSession: false
    environment: azurecloud
    audience: api://AzureADTokenExchange
    auth-type: SERVICE_PRINCIPAL
  
    TF_VERSION: 1.7.2
    TERRAFORM_CLI_PATH: /home/runner/work/_temp/5c8890e9-be42-448a-b592-0c145970d127
Running Azure CLI Login.
/usr/bin/az cloud set -n azurecloud
Done setting cloud: "azurecloud"
Federated token details:
 issuer - https://token.actions.githubusercontent.com
 subject claim - repo:meltwater/meltwater-chatbot:environment:dev
Attempting Azure CLI login by using OIDC...
Error: AADSTS700213: No matching federated identity record found for presented assertion subject 'repo:meltwater/meltwater-chatbot:environment:dev'. Please note that the matching is done using a case-sensitive comparison. Check your federated identity credential Subject, Audience and Issuer against the presented assertion. https://learn.microsoft.com/entra/workload-id/workload-identity-federation Trace ID: 41fb5824-9328-45a0-80cb-93bb24642400 Correlation ID: 865b8b30-d5bc-4fb4-baeb-0d71a3745774 Timestamp: 2024-09-03 19:34:44Z

Error: Interactive authentication is needed. Please run:
az login

Error: Login failed with Error: The process '/usr/bin/az' failed with exit code 1. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.
```

I've confirmed that the `client-id`, `tenant-id`, and `subscription-id` are all correct.  The `client-id` corresponds with this managed identity's federated credential:

![Screenshot 2024-09-06 at 3 59 29 PM](https://github.com/user-attachments/assets/15a3bf9c-d757-4375-8af6-9a04e1cb697d)

From what I can tell, the requested assertion subject `repo:meltwater/meltwater-chatbot:environment:dev` is present in the federated credential, so I'm not sure why it is not being recognized.  Any assistance would be greatly appreciated!
