### ISSUE TITLE
Error: SyntaxError: Unexpected number in JSON at position 1

### ISSUE THREAD

**Issue by pearcec** [Azure/login#64]
I have tried this numerous ways. I have recreated my SP.  I cut and paste the values in to az login to verify.  I have altered my yaml to make sure I am inputting the values correctly.  But the best I can get is this "Error: SyntaxError: Unexpected number in JSON at position 1"

Here is what I have.

```
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: <redacted>
      credentials:
        username: ${{secrets.ACR_USERNAME}}
        password: ${{secrets.ACR_PASSWORD}}
    steps:

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true
```

Example creds.

```
{
  "clientId": "<redacted>",
  "clientSecret": "<redacted>",
  "subscriptionId": "<redacted>",
  "tenantId": "<redacted>"
}
```
